### PR TITLE
Implement simple non-blocking ring buffer for communication over stlink

### PR DESCRIPTION
**Pull request by jauler**
Implemented non-blocking ring buffer for st-term.

### CODE REVIEW

**Comment by nekromant** [comment]
Thanks, sorry for getting late to merge it. Just one quick question before I merge it to experimental - have you also submitted a merge to st-term which resides in texane's st-utils repo (and is not maintained by me?).

**Comment by jauler** [comment]
Yes, texane already merged it to master :).
https://github.com/texane/stlink/commit/276ce60b092669e0e13d5d7cadcd345f63b642f6

P.S. found a little glitch with BSIZE definition in my code - fixed it.

**Comment by nekromant** [comment]
Thanks, merged!

**Comment by jauler** [comment]
Awesome :)

**Pull request merged**
